Update list-packages

diff --git a/list-packages b/list-packages
--- a/list-packages
+++ b/list-packages
@@ -2,6 +2,16 @@
 
 # This script generates a list of packages and saves it in a file called lpackages.txt
 
+# Check if the script is run as root
+check_root () { 
+		if [[ $EUID -ne 0 ]]; then
+   # If the current user is not root , print an error message
+			ECHO "Error message: This script must run as root" 
+			exit 1
+
+		fi
+}
+
 # This function lists the packages
 list_packages() {
    
